services:
    - type: web
    name: laravel-smm
    env: php
    buildCommand: composer install && php artisan key:generate && php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
